#!/bin/sh
cmake .. \
  -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DBUILD_UNITTESTS=OFF \
  -DBUILD_EXAMPLES=TRUE \
  -DBUILD_BENCHMARKS=OFF \
  -DBUILD_STATIC=ON \
  -DBUILD_SHARED=OFF \
  -DWITH_OPENMP=OFF \
  -DNATIVE_SIZE=64
  
