#!/bin/bash
#EXAMPLE=advanced-ckks-bootstrapping
EXAMPLE=simple-ckks-bootstrapping

case $MODE in
  release)
  ;;

  release-no-bas)
  FLAGS="-DBASALISC_USE_OPENFHE_DEFAULT"
  ;;

  debug)
  FLAGS="-g"
  ;;

  debug-prof)
  FLAGS="-g -pg"
  ;;

  debug-no-bas)
  FLAGS="-g -pg -DBASALISC_USE_OPENFHE_DEFAULT"
  ;;

  *)
    echo "Unknown mode $MODE"
    echo "MODE = release | release-no-bas | debug | debug-no-bas"
    exit 1
esac

BUILD="build-$MODE"

clang++ \
  -I src/pke/include \
  -I src/core/include \
  -I src/math/include \
  -I $BUILD/src/core \
  -I third-party/cereal/include/ \
  -I src/binfhe/include \
     src/pke/examples/$EXAMPLE.cpp \
   -o "$EXAMPLE-$MODE" \
   $FLAGS \
  -L $BUILD/lib \
  -lOPENFHEpke_static \
  -lOPENFHEcore_static \
  -lOPENFHEbinfhe_static \
  --std=c++17

